# 生产环境配置
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: comm-sys
  
  # 数据库配置
  datasource:
    url: jdbc:sqlite:data/comm_sys.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: CommSysHikariCP

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: false
        use_sql_comments: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

# 日志配置
logging:
  level:
    com.commsys: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/app.log
    max-size: 100MB
    max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# 自定义配置
app:
  # 数据库类型：mysql 或 sqlite
  database:
    type: sqlite
  # 分页配置
  page:
    default-size: 10
    max-size: 100
  # 文件上传配置
  upload:
    path: ./uploads
    max-size: 10MB
