# SQLite数据库配置
spring:
  datasource:
    url: jdbc:sqlite:common_sys.db
    driver-class-name: org.sqlite.JDBC
  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect

app:
  database:
    type: sqlite
